### ISSUE TITLE
Distribute soap4r-spox as a gem

### ISSUE THREAD

**Issue by fnando** [spox/soap4r-spox#4]
We need to distribute this library as gem so we can use it with Rails 3.0.0+ and latest bundler.

**Comment by spox** [comment]
I have some free time tonight to catch up on some of these issues. I'll push a gem release out as well.

**Comment by fnando** [comment]
Nice! :)

**Comment by johngrimes** [comment]
+1 to this one!

Myself and others are waiting on this one so that we can work on switching dependencies on some downstream libraries that want to become Ruby 1.9 compliant.

**Comment by stonefield** [comment]
+1 to this - tonight:-)

**Comment by ababkin** [comment]
guess 'tonight' never happened?

**Comment by chrisroberts** [comment]
@ababkin thanks for the bump. apparently "tonight" was stuck in a time vortex or something for a bit.
